### ISSUE TITLE
Problem with uploadDir path.

### ISSUE THREAD

**Issue by gabrielsme** [ankitpokhrel/laravel-image#1]
I can`t access the application after the last update.

> Exception in Local.php line 104:
> Impossible to create the root directory "".
> in Local.php line 104
> at Local->ensureDirectory(null) in Local.php line 76
> at Local->__construct(null) in ImageUploadServiceProvider.php line 56
> at ImageUploadServiceProvider->LaravelImage{closure}(object(Application), array()) in Container.php line 738
> at Container->build(object(Closure), array()) in Container.php line 631
> at Container->make('\League\Glide\Server', array()) in Application.php line 674
> at Application->make('\League\Glide\Server', array()) in Container.php line 633
> at Container->make('League\Glide\Server', array()) in Application.php line 674
> at Application->make('League\Glide\Server') in RouteDependencyResolverTrait.php line 87
> at Route->transformDependency(object(ReflectionParameter), array('path' => '/'), array('path' => '/')) in RouteDependencyResolverTrait.php line 59
> at Route->resolveMethodDependencies(array('path' => '/'), object(ReflectionFunction)) in Route.php line 152
> at Route->runCallable(object(Request)) in Route.php line 130
> at Route->run(object(Request)) in Router.php line 708
> at Router->Illuminate\Routing{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
> at Pipeline->Illuminate\Pipeline{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
> at Pipeline->then(object(Closure)) in Router.php line 710
> at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 673
> at Router->dispatchToRoute(object(Request)) in Router.php line 635
> at Router->dispatch(object(Request)) in Kernel.php line 236
> at Kernel->Illuminate\Foundation\Http{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
> at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in Debugbar.php line 49
> at Debugbar->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(Debugbar), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in ShareErrorsFromSession.php line 49
> at ShareErrorsFromSession->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in StartSession.php line 62
> at StartSession->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
> at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in EncryptCookies.php line 59
> at EncryptCookies->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
> at CheckForMaintenanceMode->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
> at Pipeline->then(object(Closure)) in Kernel.php line 122
> at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 87
> at Kernel->handle(object(Request)) in index.php line 53

**Comment by ankitpokhrel** [comment]
@gabrielsme I cannot reproduce the issue. Do you have configuration file `laravelimage.php`? If not run `php artisan vendor:publish --provider="LaravelImage\ImageUploadServiceProvider"`. This will create a config file called `laravelimage.php`.

**Comment by samundra** [comment]
@gabrielsme I also found the similar issue but in my case I had to give 777 permission to `storage` folder. So basically everything worked after I gave

``` bash
chmod 777 storage -R

```

I tested this on `Laravel 5.3 version`.

**Comment by ankitpokhrel** [comment]
@gabrielsme I found similar bug in `5.3`. Note that the plugin is not yet production ready.

**Comment by ankitpokhrel** [comment]
Related, Ref: 59f45ef
